### ISSUE TITLE
See test status in test source editor

### ISSUE THREAD

**Issue by ryan-gustafson** [MoreUnit/MoreUnit-Eclipse#36]
There are times where it would be very convenient to run all the tests (CTRL-R), and see in the test source editor an indication of which tests are failing.  In particular, when a refactor causes a systematic breakage that is best worked via the test source code, order and _not_ via the test run failure view.  A marker on the left side of the test source editor would suffice, along with the hover showing the failure reason.  The set of markers could correlate with the currently selected test run in the history.  I write this assuming Eclipse/JUnit.

Without such a feature there's a lot of extra motion to identify failing tests, and to work through fixing nearby/related tests in source order.  Running each test individually works, but is cumbersome as you generally need to do it at least once to find failures, and then if you make any changes go through it again.

I also find myself commenting out large blocks of test methods in the lower half of the test class, using CTRL-R to get the top half all green, then uncommenting the next test, getting it to pass, and continuing on until everything is green. Unfortunately, this tends to hamper refactoring commands and feedback from the compiler on the commented out code; additionally automatic organization of imports can remove stuff only used by the commented code.

Seeing failures correlated to the test source editor would be a huge time saver.

I suppose similar information could be shown in the non-test source editors, to indicate which methods have failing tests.

**Comment by ndemengel** [comment]
Hi Ryan,

Maybe I misunderstood your need, but it seems to me that an equally useful solution would be that the JUnit view proposes an option to present the results in the order of the test methods (and also, another great option would be to present them alphabetically, as IntelliJ does). May I suggest that you proposes it to the Eclipse developers?

As for your proposal, it reminds me of the Infinitest plug-in, which as far as I remember does exactly that: it automatically runs tests related to your code changes and it places error markers in both the test and production code editors to report failures. The drawback though, is that this plug-in is only suitable for suite of real quick unit tests.

This answer isn't a no-go in any way, especially since I'm not active on this project anymore, but I thought that maybe these alternative options could be of interest to you.

**Comment by ndemengel** [comment]
You can watch Infinitest in action here: https://www.youtube.com/watch?v=037B6mfWjWs
