### ISSUE TITLE
Remove any references to sourceforge

### ISSUE THREAD

**Issue by justin-wesley** [MoreUnit/MoreUnit-Eclipse#40]
Sourceforge is no longer reputable with more and more companies are blocking access to it. The eclipse update site should be moved elsewhere. Also, the website should be hosted somewhere else as well. Possible moving it to github.io or the project WIKI.

**Comment by gianasista** [comment]
Thank you for your feedback. You are right.
@ndemengel: What do you think? For an interim time we can deploy releases to the old sourceforge site too.

**Comment by ndemengel** [comment]
Hi Justin,

I totally agree, and it shouldn't be difficult to move everything to a gh-pages branch so that it is served by Github. As an additional benefit, new contributors to the project wouldn't need credentials on Sourceforge to help.
I can find some time next week to look a it.

@gianasista indeed, I find it wise to still deploy to Sourceforge at first. Also it would be great to find a way to alert our users about this change. I don't know if Eclipse has something like the release notes popup of IntelliJ, but that would be a good way to notify them.

**Comment by ndemengel** [comment]
Just made the following:

- created Github Pages for our organization: https://moreunit.github.io. To update it, just push changes to https://github.com/MoreUnit/moreunit.github.io
- exposed our existing website as Github Pages as well: https://moreunit.github.io/MoreUnit-Eclipse/. Our "homepage" directory has been renamed into "docs", the only name supported to directly expose a subdirectory. To update the website, just push changes
- created a new Eclipse update site, as a "Github Pages only" repo: https://moreunit.github.io/eclipse-update-site (try it by appending artifacts.jar to this URL). As for the other sites, we just have to push changes to https://github.com/MoreUnit/eclipse-update-site to update artifacts
- modified the release script to push artifacts into this repo.

Next steps:
- find a way to advertise the new update site from within the plugin
- publish a new release
- remove all Sourceforge related stuff
- bonus: remove the manual step required to attach our all-in-one-zip update site to the Github release ([example here](https://github.com/MoreUnit/MoreUnit-Eclipse/releases/tag/v3.1.1)), using [Github API](https://developer.github.com/v3/repos/releases/). Alternatively, we can either stop publishing this artifact, or push it to https://github.com/MoreUnit/eclipse-update-site as well, and put a direct link into our doc (I would prefer the latter: many users still download the all-in-one zip, and that solution is simple to set-up).

**Comment by apupier** [comment]
@ndemengel the repo https://moreunit.github.io/MoreUnit-Eclipse/#download is giving a 404 currently. is it because we have made no new release since you modified script to point there?

**Comment by apupier** [comment]
ok the correct update site is https://github.com/MoreUnit/eclipse-update-site , I will update the doc page

**Comment by ndemengel** [comment]
@apupier well, I can access the page https://moreunit.github.io/MoreUnit-Eclipse/#download and the links in it. As for http://moreunit.sourceforge.net/update-site/, it gives me a 403, but this is expected since we never configured it to list the items present in it. Eclipse directly accesses http://moreunit.sourceforge.net/update-site/artifacts.jar, which works well.

**Comment by ndemengel** [comment]
And indeed, the new place is https://github.com/MoreUnit/eclipse-update-site

**Comment by ndemengel** [comment]
And by the way, thanks for taking over!

**Comment by apupier** [comment]
there is a reference to http://moreunit.sourceforge.net/schemas/mocking-templates.xsd in severla files.
I guess we can move the xsd to github and update these references?

**Comment by ndemengel** [comment]
Sure
